export const getPosts = {
  REQUEST: 'POST_LIST_REQUEST',
  SUCCESS: 'POST_LIST_SUCCESS',
  FAILURE: 'POST_LIST_FAILURE',
};

export const retrieveSinglePost = {
  REQUEST: 'POST_SINGLE_REQUEST',
  SUCCESS: 'POST_SINGLE_SUCCESS',
  FAILURE: 'POST_SINGLE_FAILURE',
  RESET: 'POST_SINGLE_RESET',
};

export const makePost = {
  REQUEST: 'POST_CREATE_REQUEST',
  SUCCESS: 'POST_CREATE_SUCCESS',
  FAILURE: 'POST_CREATE_FAILURE',
  RESET: 'POST_CREATE_RESET',
};

export const patchPost = {
  REQUEST: 'POST_UPDATE_REQUEST',
  SUCCESS: 'POST_UPDATE_SUCCESS',
  FAILURE: 'POST_UPDATE_FAILURE',
  RESET: 'POST_UPDATE_RESET',
};

export const removePost = {
  REQUEST: 'POST_REMOVE_REQUEST',
  SUCCESS: 'POST_REMOVE_SUCCESS',
  FAILURE: 'POST_REMOVE_FAILURE',
  RESET: 'POST_REMOVE_RESET',
};
