export const loginTypes = {
  REQUEST: 'USER_LOGIN_REQUEST',
  SUCCESS: 'USER_LOGIN_SUCCESS',
  FAILURE: 'USER_LOGIN_FAILURE',
  LOGOUT: 'USER_LOGOUT',
};
export const logoutTypes = {
  REQUEST: 'USER_LOGOUT_REQUEST',
  SUCCESS: 'USER_LOGOUT_SUCCESS',
  FAILURE: 'USER_LOGOUT_FAILURE',
};
export const registerTypes = {
  REQUEST: 'USER_REGISTER_REQUEST',
  SUCCESS: 'USER_REGISTER_SUCCESS',
  FALIURE: 'USER_REGISTER_FAILURE',
  LOGOUT: 'USER_REGISTER_LOGOUT',
};
export const profileTypes = {
  REQUEST: 'USER_PROFILE_REQUEST',
  SUCCESS: 'USER_PROFILE_SUCCESS',
  FALIURE: 'USER_PROFILE_FAILURE',
};
export const updateProfileTypes = {
  REQUEST: 'USER_UPDATE_PROFILE_REQUEST',
  SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
  FALIURE: 'USER_UPDATE_PROFILE_FAILURE',
};
